---
title: "Review: Ostrom, E. (2010). Beyond Markets and States: Polycentric Governance
  of Complex Economic Systems."
author: JordanInskeep
date: '2022-11-09'
slug: ostrom2010-review
categories:
  - review
tags:
  - polycentricity
  - Ostrom
  - IAD
  - SES
draft: no
---

## Ostrom, E. (2010). Beyond Markets and States: Polycentric Governance of Complex Economic Systems. *American Economic Review*, *100*(3), Article 3. [https://doi.org/10.1257/aer.100.3.641](https://doi.org/10.1257/aer.100.3.641)

### Intro

This is a revised version of the lectures given by Lin Ostrom after receiving the Nobel Prize for Economic Science

It is an attempt to solidify Institutional Analysis and Development Framework (IAD) as a way of assessing complexity in economic but more broadly complex social systems. The article uses the concept of polycentricity to describe institutional arrangements that involve multiple levels of diverse stakeholder groups that work at different scales and effect outcomes.

“Due to the complexity of broader field settings, one needs to develop more configural approaches to the study of factors that enhance or detract from the emergence and robustness of self-organized efforts within multilevel, polycentric systems.” (Ostrom, 2010 page 642)

### Self-Organization and Politics in IAD

Self-organization is in this context often a discussion around the development of representative constitutional arrangements from the bottom-up [see @ostrom1961; trako2019]. For as forward thinking IAD was the limited empirically focused scope of the Ostrom’s work failed to test other more radical or fringe political arrangements. This could just as easily be applied to more directly democratic or anarchistic systems. In a lecture on Youtube ([https://youtu.be/LqC7xG8fxHw?t=461](https://youtu.be/LqC7xG8fxHw?t=461)) Lin discusses the growing use of her work to establish ‘community control’ as a panacea. She is careful to avoid a normative political position on markets, state control, or community control. In the video she states, “we have to understand under what conditions, and what attributes of those systems are the important variables.” My questions is what is important? and how do we understand what the different outcomes of “successful” state control, “successful” markets, and “successful” communities are? This is a inherently political questions, in each setting there will be winners and losers, environmental and social costs and benefits, and most importantly long lasting effects on human and human societies.

### IAD Framework

She goes on to explain the development of the types of goods typology, which uses two dimensions along subtractability and excludability to produce four types, of goods. It could be important to spend more time discussing the implications of scarcity and induced demand on this typology. In general though, private goods could be common-pool resources if we didn’t exclude them through commodification. All private goods could be distributed through libraries or other sharing systems.

The IAD framework is rooted in the idea of actions situations which are the locations which decisions are made and outcomes are determined. It is also effected by external variables. Outcomes are also feedback into these actions situations and external variables. This process is passive and active. Individuals can intentionally work towards outcomes which will effect external variables and action situations.

Internal to actions situations are variables which are determined by seven rules. Each rule can have any number of sub-types. For example in the lecture mentioned above Lin says that they had empirically found up to 80+ boundary rules that are in-use in the different governance systems.

### Ostrom’s Design Principles

Based on these different rules, Ostrom was able to build a list of important design principles which are present in many “long-lasting” institutions.

“IA. User Boundaries: Clear and locally understood boundaries between legitimate users and nonusers are present.  
1B. Resource Boundaries: Clear boundaries that separate a specific common-pool resource from a larger social-ecological system are present.    
2A. Congruence with Local Conditions: Appropriation and provision rules are congruent with local social and environmental conditions.  
2B. Appropriation and Provision: Appropriation rules are congruent with provision rules; the distribution of costs is proportional to the distribution of benefits.  
3. Collective Choice Arrangements: Most individuals affected by a resource regime are authorized to participate in making and modifying its rules.  
4A. Monitoring Users: Individuals who are accountable to or are the users monitor the appropriation and provision levels of the users.  
4B. Monitoring the Resource: Individuals who are accountable to or are the users monitor the condition of the resource. 
5. Graduated Sanctions: Sanctions for rule violations start very low but become stronger if a user repeatedly violates a rule.  
6. Conflict Resolution Mechanisms: Rapid, low cost, local arenas exist for resolving conflicts among users or with officials.  
7. Minimal Recognition of Rights: The rights of local users to make their own rules are recognized by the government.  
8. Nested Enterprises: When a common-pool resource is closely connected to a larger social-ecological system, governance activities are organized in multiple nested layers.” (Ostrom, 2010, page 653)

### Theoretical Developments

“We need to develop a better theoretical understanding of human behavior as well as of the impact of the diverse contexts that humans face.” (Ostrom, 2010, page 659)

The recent developments in evolutionary anthropology and archeology are important to include in this revised understand of human behavior. These developments encompass both individual evolutionary psychology, and the diversity of contexts from which those psychologies were evolved, including a long history of large-scale cooperation (Boyd and Richerson, 2022; Glowacki and Lew-Levy, 2022; Wengrow and Graeber, 2015; Henrich and Muthukrishna, 2021). Ostrom focuses on the ability for humans to learn, the use of heuristics, and the use of norms or preferences related to benefiting others. Each of these topics will be explored in later reviews (Moyson et al., 2017; Jones, 2017). She also mentions the importance of trust in the development of reciprocity among actors.

In address micro-situations, that is the moments and setting in which an individuals are interacting and decisions are being made, Ostrom discusses the factors the cooperating in that situation. She mentions six, 1. Communication is possible, 2. Reputations and histories of others are known, 3. Individual cooperation has group benefits, 4. Entry and Exit capabilities, 5. Long time horizons, and 5. Internally agreed upon sanctions.

In discussing broader contexts, she employs social-ecological systems (SES) theory, where she shows out actions situations are embedded within broader set of contextual variables. At the highest conceptual level these are, endogenously, the social, economic and political setting and related ecosystems, and endogenously, the resource system, the resource units, the governance system and the users. Each variable is then unpacked at lower levels. More on this on the review of Ostrom (2009).

### Moving Forward

In closing, Ostrom reemphasized the importance of trust.

“Building trust in one another and developing institutional rules that are well matched to the ecological systems being used are of central importance for solving social dilemmas. The surprising but repeated finding that users of resources that are in relatively good condition --- or even improving --- do invest in various ways of monitoring one another relates to the core problem of building trust.” (Ostrom, 2010, p. 664)

This discussion of trust begs the questions of how do institutions build trust? and how can we move towards a more trusting political arrangement. For this it will be important to consider group based decision making theories and processes. Consensus, structured decision making, directly democratic forms of politics, all hold potential for creating trust through deliberative and face-to-face decisions making. This is especially true if we want to move towards a commons based economy, in which all people have their basic needs meet and have agency in the systems that determine how those needs are meet.

Certainly I will be accused of evoking a panacea, or being to normative. This falls into the same trap which Ostrom falls into in discussing “community control.” Anarchism and other directly democratic governance structure are not a panacea, they are an anti-panacea. They take seriously the implications of other forms of governance; such as state power and markets, especially the tendency that both of these forms of governance have shown through history to create a homogeneous society where diversity is consumed for the sake of efficiency, productivity or profit. This is the analysis that is missing in much of the current policy scholarship and research. In Lin’s own words an analysis that could better “facilitate the development of institutions that bring out the best in humans” not the worst, as history has shown.

“Extensive empirical research leads me to argue that instead, a core goal of public policy should be to facilitate the development of institutions that bring out the best in humans. We need to ask how diverse polycentric institutions help or hinder the innovativeness, learning, adapting, trustworthiness, levels of cooperation of participants, and the achievement of more effective, equitable, and sustainable outcomes at multiple scales.” (Ostrom, 2010, p. 665)

We must embrace complexity.

### References

Boyd, R., & Richerson, P. J. (2022). Large‐scale cooperation in small‐scale foraging societies. Evolutionary Anthropology: Issues, News, and Reviews, 31(4), 175–198. https://doi.org/10.1002/evan.21944

Glowacki, L., & Lew-Levy, S. (2022). How small-scale societies achieve large-scale cooperation. Current Opinion in Psychology, 44, 44–48. https://doi.org/10.1016/j.copsyc.2021.08.026

Henrich, J., & Muthukrishna, M. (2021). The Origins and Psychology of Human Cooperation. Annual Review of Psychology, 72(1), 207–240. https://doi.org/10.1146/annurev-psych-081920-042106

Jones, B. D. (2017). Behavioral rationality as a foundation for public policy studies. Cognitive Systems Research, 43, 63–75. https://doi.org/10.1016/j.cogsys.2017.01.003

Moyson, S., Scholten, P., & Weible, C. M. (2017). Policy learning and policy change: Theorizing their relations from different perspectives. Policy and Society, 36(2), 161–177. https://doi.org/10.1080/14494035.2017.1331879

Ostrom, E. (2005). Understanding institutional diversity. Princeton University Press.

Ostrom, E. (2009). A General Framework for Analyzing Sustainability of Social-Ecological Systems. Science, 325(5939), Article 5939. https://doi.org/10.1126/science.1172133

Wengrow, D., & Graeber, D. (2015). Farewell to the ‘childhood of man’: Ritual, seasonality, and the origins of inequality: Farewell to the ‘childhood of man.’ Journal of the Royal Anthropological Institute, 21(3), 597–619. https://doi.org/10.1111/1467-9655.12247



